import Head from 'next/head'
import Image from 'next/Image'
import Link from 'next/Link'



export default function Project({data}) {

  console.log(data)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        
        <div>
    
            <h1>{data.name}</h1>
            <p>Fork Count: {data.forks_count}</p>
            <p>Language: {data.language}</p>
            <p>Start Count: {data.watchers}</p>
            <p>clone_url: {data.clone_url}</p>
            <p>ssh_url: {data.ssh_url}</p>
            <p>visibility: {data.visibility}</p>
            click here <p>original Project Repo:   <Link href={data.html_url}>  click here </Link> </p>




          {/* <Image src={data.avatar_url} width={200} height={200} alt="img" /> */}
        </div>
        
        
      </main>

      
    </div>
  )
}

export async function getStaticPaths(){
  let res = await fetch("https://api.github.com/search/repositories?q=user:riteshf+fork:true&sort=updated&per_page=10&type=Repositories")
  let data = await res.json()

  return{
    paths:data.items.map((el)=>({
        params:{id:el.id.toString()}
    })),
    fallback:false
  }
}


export async function getStaticProps(context){
    const {params:{id}}= context
    // console.log(typeof(Number(id)))
  let res = await fetch(`https://api.github.com/search/repositories?q=user:riteshf+fork:true&sort=updated&per_page=10&type=Repositories`)
  let data = await res.json()

  let newData = data.items.filter((el)=>(el.id===Number(id)))
// console.log(data)
let newData2 = newData[0]
  return{
    props:{
      data:newData2
    }
  }
}
