import Head from 'next/head'
import Image from 'next/Image'
import Link from 'next/Link'



export default function Projects({data}) {
  console.log(data)
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <div>
            {
                data.map((el)=>{return <Link href={`/projects/${el.id}`} key={el.id}>
                    <h1>{el.name}</h1>
                    <p>Fork Count: {data.forks_count}</p>
                    <p>Language: {data.language}</p>
                    <p>Start Count: {data.watchers}</p>
                    <p>following: {data.following}</p>
                    </Link>
                })
            }
           
          {/* <Image src={data.avatar_url} width={200} height={200} alt="img" /> */}
        </div>
        
        
      </main>

      
    </div>
  )
}


export async function getServerSideProps(){
  let res = await fetch("https://api.github.com/search/repositories?q=user:riteshf+fork:true&sort=updated&per_page=10&type=Repositories")
  let data = await res.json()
  return{
    props:{
      data:data.items
    }
  }
}